mainfolder: /home/jb/Workspace/Python/HiM_merFISH_analysis/merFISH_simulation
destinationfolder : /home/jb/Workspace/Python/HiM_merFISH_analysis/merFISH_simulation/Simulated_images

codebook:
  codebookfolder: /home/jb/Workspace/Python/HiM_merFISH_analysis/merFISH_simulation/Simulated_data_for_MERlin/merfish-parameters/codebooks/test_codebook.csv

image:
  width : 256
  height : 256
  psf_FWHM_nm : 250
  pixel_size_nm : 97

acquisition_data:
  nROI : 1
  rounds : 16
  
fiducial:
  number : 25
  channel : 2
  background_intensity : 0
  average_drift_px : 1
  average_beads_intensity : 2000
  
readout_probe:
  number_detections_per_image : 500   
  number_selected_loci : 2
  channels : 1
  background_intensity : 1000
  average_readout_intensity : 700
