mainfolder: /home/jb/Workspace/Python/merFISH_simulation
destinationfolder : /home/jb/Workspace/Python/merFISH_simulation/Simulated_data

image:
  width : 256
  height : 256
  psf_FWHM_nm : 250
  pixel_size_nm : 97

acquisition_data:
  nROI : 5
  rounds : 16
  
fiducial:
  number : 5
  channel : 2
  background_intensity : 1000
  
readout_probe:
  number : 100   
  channels : 1
  background_intensity : 0

codebook:
  codebookfolder: /home/jb/Workspace/Python/merFISH_simulation/test_data/test_codebook.csv
