mainfolder: /home/jb/Workspace/Python/HiM_segmentation_simulation/3D_loci_simulation
destinationfolder : /home/jb/Desktop/Simulation_3D
psffolder : /home/jb/Workspace/Python/HiM_segmentation_simulation/3D_loci_simulation/psf_analyze_npy

image:
  width : 256 # in pix
  height : 256 # in pix
  pixel_size_nm : 100
  number_z_planes : 60
  z_spacing_nm : 250
  background_intensity : [15,70]
  background_step : [0.2,1]
  intensity_single_probe : 20
  intensity_threshold : 21.8

acquisition_data:
  nROI : 10

ground_truth :
  simulated_psf_width : 400 # in nm
  simulated_psf_height : 500 # in nm

psf :
  psf_width : 101 # in pixel - size of the image used for the simulation
  psf_height : 101
  psf_planes : 131 # number of planes
  z_spacing_psf_nm : 100 # Spacing in nm between successive planes for the psf file

detection:
  number_detections_per_image : 50 # average number of detections per field of view
  number_false_positive_data : 2500 # average number of false positive (single probe)
  minimum_depth_um : 1 # to avoid having detections too close to the first or last frames
  loci_size_kb : 3
  number_probes : 45
  beta_min : 0.3
  beta_max : 0.55
  gamma_min : 30
  gamma_max : 100
  diploid_pair_probability : 0.9
  average_paired_distance_nm : 70 # in nm
  probe_hybridization_probability : [0.1, 0.7] # probability for a single probe to hybridize to a loci
